language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
gemfile:
  - test/gemfiles/Gemfile.sqlite3
  - test/gemfiles/Gemfile.rails-3.2.x
  - test/gemfiles/Gemfile.rails-4.0.x
  # - test/gemfiles/Gemfile.rails-4.1.x
matrix:
  exclude:
    - { rvm: 1.8.7, gemfile: test/gemfiles/Gemfile.rails-4.0.x }
    # - { rvm: 1.8.7, gemfile: test/gemfiles/Gemfile.rails-4.1.x }
    - { rvm: 1.9.2, gemfile: test/gemfiles/Gemfile.rails-4.0.x }
    # - { rvm: 1.9.2, gemfile: test/gemfiles/Gemfile.rails-4.1.x }
    # - { rvm: 1.9.3, gemfile: test/gemfiles/Gemfile.rails-4.1.x }
    - { rvm: 2.0.0, gemfile: test/gemfiles/Gemfile.rails-3.2.x }
    - { rvm: 2.1,   gemfile: test/gemfiles/Gemfile.rails-3.2.x }
notifications:
  recipients:
    email:
      - cedric@howe.net
  on_success: change
  on_failure: always
